
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-05
owner: ucsb-cs156-f25
repo_name: team02-f25-05
pull_requests: [{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"restore-2e55cf9c","number":136,"title":"Restore repository to snapshot 2e55cf9c","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/136"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"restore-981ced13","number":135,"title":"Restore repository to snapshot 981ced13","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/135"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-edit","number":133,"title":"BS - HelpRequest Edit Page","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/133"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-index","number":129,"title":"BS - HelpRequest Index","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/129"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-create2","number":128,"title":"BS -  HelpRequest Create Page","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/128"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-placeholder2","number":126,"title":"BS - Help Request placeholder2","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/126"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-table2","number":113,"title":"BS - HelpRequest Table2","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/113"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-form2","number":104,"title":"BS -  HelpRequest Form New Attempt","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/104"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-fixtures","number":71,"title":"BS - Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/71"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-backend","number":69,"title":"BS - Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/69"}]
