
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-05
owner: ucsb-cs156-f25
repo_name: team02-f25-05
pull_requests: [{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-UCSBOrganization-placeholder-pages","number":70,"title":"MF - Create placeholder pages for frontend Index, Edit, Create for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/70"},{"author":{"id":"MDQ6VXNlcjkwNTI5Mzc0","is_bot":false,"login":"bsen1","name":"Brian Sen"},"headRefName":"bs-HelpRequest-backend","number":69,"title":"BS - Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/69"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-UCSBOrganization-table","number":68,"title":"MF - create USCBOrganization frontend table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/68"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-RecommendationRequest-Form-Component","number":67,"title":"HY - Form for Recommendation Request","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/67"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-RecommendationRequest-fixtures","number":66,"title":"HY - add JavaScript Fixtures for RecommendationRequesr Table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/66"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-RecommendationRequest-backend","number":65,"title":"HY - Copy backend CURD operations from team01 for the RecommendationRequest table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/65"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-UCSBOrganization-form","number":64,"title":"MF - added UCSBOrganization form","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/64"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-UCSBOrganization-fixtures","number":63,"title":"MF - add JavaScript Fixtures for UCSBOrganization Table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/63"},{"author":{"id":"U_kgDODfPQcg","is_bot":false,"login":"monraphael-maker","name":"mr-maker"},"headRefName":"MF-UCSBOrganization-backend","number":62,"title":"MF - copy backend CRUD operations from team01 for the UCSBOrganization Table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/62"}]
