
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-05
owner: ucsb-cs156-f25
repo_name: team02-f25-05
pull_requests: [{"author":{"id":"U_kgDOCM7mwQ","is_bot":false,"login":"jasminetan0510","name":""},"headRefName":"jt-UCSBDiningCommonsMenuItems-integration-tests","number":156,"title":"jt - add integration tests for UCSBDiningCommonsMenuItems Controller endpoints","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/156"}]
