
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-05
owner: ucsb-cs156-f25
repo_name: team02-f25-05
pull_requests: [{"author":{"id":"U_kgDOCM7mwQ","is_bot":false,"login":"jasminetan0510","name":""},"headRefName":"jt/hotfix","number":164,"title":"running formatting","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/164"},{"author":{"id":"U_kgDOCM7mwQ","is_bot":false,"login":"jasminetan0510","name":""},"headRefName":"jt-UCSBDiningCommonsMenuItems-e2e-tests","number":163,"title":"jt - add e2e tests for UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/163"},{"author":{"id":"U_kgDOCEli4w","is_bot":false,"login":"Hechenjin","name":""},"headRefName":"HY-recommendationRequest-e2e-tests","number":162,"title":"HY - added e2e tests for Recommendation Request","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/162"},{"author":{"id":"MDQ6VXNlcjg4MTE4MjQy","is_bot":false,"login":"amelvinmathew","name":""},"headRefName":"mm-MenuItemReviews-integration-test","number":160,"title":"mm - added integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-05/pull/160"}]
